-- CreateTable
CREATE TABLE "animals" (
    "id" SERIAL NOT NULL,
    "id_animal" INTEGER NOT NULL,
    "id_cobertura" INTEGER,
    "nome_animal" TEXT NOT NULL,
    "registro_abqm" TEXT NOT NULL,
    "registro_original" TEXT,
    "sufixo_nome_animal" TEXT,
    "sexo_animal" TEXT NOT NULL,
    "dt_nascimento" TEXT NOT NULL,
    "dt_castracao" TEXT,
    "dt_alteracao" TEXT,
    "dt_obito" TEXT,
    "dsc_grau_sangue" TEXT NOT NULL,
    "ds_pelagem" TEXT NOT NULL,
    "nome_proprietario" TEXT NOT NULL,
    "nome_comprador" TEXT NOT NULL,
    "nome_criador" TEXT NOT NULL,
    "id_pai" INTEGER,
    "nome_pai" TEXT,
    "registro_pai" TEXT,
    "id_mae" INTEGER,
    "nome_mae" TEXT,
    "registro_mae" TEXT,
    "tipificacao_sanguinea" INTEGER,
    "DNA_LINK" TEXT,
    "hypp" INTEGER,
    "hypp_string" TEXT,
    "five_panel" TEXT,
    "motivo_castracao" TEXT,
    "path_fotos" TEXT,
    "nro_chip" TEXT,
    "qtd_chip" INTEGER NOT NULL,
    "dt_implantacao" TEXT,
    "alienado" TEXT,
    "arrendado" TEXT,
    "chave" TEXT NOT NULL,
    "dt_fim_temp_transf_emb" TEXT,
    "pontos" INTEGER NOT NULL,
    "pk_imagem" TEXT,
    "placa" INTEGER NOT NULL,
    "pdf" TEXT,
    "artigo_43" TEXT,
    "resenha" TEXT,
    "situacao" TEXT NOT NULL,
    "id_resultado_laboratorio" INTEGER,
    "imagens" TEXT,
    "acessos" INTEGER NOT NULL,
    "situacao_laboratorio" TEXT,
    "impressive" INTEGER,
    "num_preregistro" TEXT,
    "dt_importacao" TEXT,
    "dt_inclusao_lancamento" TEXT,
    "dt_inclusao_situacao" TEXT,
    "dt_inclusao" TEXT,
    "dt_envio_doc" TEXT,
    "linkchip" TEXT,
    "possui_campanha" INTEGER NOT NULL,
    "status_esportes" INTEGER,
    "id_criador" INTEGER,
    "id_proprietario" INTEGER,
    "id_laboratorio" INTEGER,
    "exibe_laudo" TEXT NOT NULL,
    "acesso_laboratorio" TEXT NOT NULL,
    "situacao_esportes" TEXT,
    "hall_da_fama" INTEGER,
    "qtdFilhos" INTEGER,
    "somaPontos" INTEGER,
    "qtdFilhosComPontos" INTEGER,
    "hall_da_fama_pessoa" INTEGER,
    "qtdFilhosMachoPontuados" INTEGER,
    "qtdFilhosFemeaPontuados" INTEGER,
    "qtdFilhosMacho" INTEGER,
    "qtdFilhosFemea" INTEGER,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "animals_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "animals_id_animal_key" ON "animals"("id_animal");

-- AddForeignKey
ALTER TABLE "animals" ADD CONSTRAINT "animals_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
