services:
  # api:
  #   build:
  #     context: ./API-EQUICONTROL
  #     dockerfile: Dockerfile
  #   image: apiequicontrolimage
  #   container_name: api
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - "db"

  db:
    image: "postgres:13.21-alpine3.20"
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dbEquicontrol
    volumes:
      - dbVolume:/var/lib/postgresql/data
    
volumes:
  dbVolume: