-- CreateTable
CREATE TABLE "users" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "nome" TEXT NOT NULL,
    "senha" TEXT NOT NULL,
    "dt_cadastro" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "animals" (
    "id" SERIAL NOT NULL,
    "id_animal" INTEGER NOT NULL,
    "id_cobertura" INTEGER,
    "nome_animal" TEXT NOT NULL,
    "registro_abqm" TEXT NOT NULL,
    "registro_original" TEXT,
    "sufixo_nome_animal" TEXT,
    "sexo_animal" TEXT NOT NULL,
    "dt_nascimento" TEXT NOT NULL,
    "dt_castracao" TEXT,
    "dt_alteracao" TEXT,
    "dt_obito" TEXT,
    "dsc_grau_sangue" TEXT NOT NULL,
    "ds_pelagem" TEXT NOT NULL,
    "nome_proprietario" TEXT NOT NULL,
    "nome_comprador" TEXT NOT NULL,
    "nome_criador" TEXT NOT NULL,
    "id_pai" INTEGER,
    "nome_pai" TEXT,
    "registro_pai" TEXT,
    "id_mae" INTEGER,
    "nome_mae" TEXT,
    "registro_mae" TEXT,
    "tipificacao_sanguinea" INTEGER,
    "DNA_LINK" TEXT,
    "hypp" INTEGER,
    "hypp_string" TEXT,
    "five_panel" TEXT,
    "motivo_castracao" TEXT,
    "path_fotos" TEXT,
    "nro_chip" TEXT,
    "qtd_chip" INTEGER NOT NULL,
    "dt_implantacao" TEXT,
    "alienado" TEXT,
    "arrendado" TEXT,
    "chave" TEXT NOT NULL,
    "dt_fim_temp_transf_emb" TEXT,
    "pontos" INTEGER NOT NULL,
    "pk_imagem" TEXT,
    "placa" INTEGER NOT NULL,
    "pdf" TEXT,
    "artigo_43" TEXT,
    "resenha" TEXT,
    "situacao" TEXT NOT NULL,
    "id_resultado_laboratorio" INTEGER,
    "imagens" TEXT,
    "acessos" INTEGER NOT NULL,
    "situacao_laboratorio" TEXT,
    "impressive" INTEGER,
    "num_preregistro" TEXT,
    "dt_importacao" TEXT,
    "dt_inclusao_lancamento" TEXT,
    "dt_inclusao_situacao" TEXT,
    "dt_inclusao" TEXT,
    "dt_envio_doc" TEXT,
    "linkchip" TEXT,
    "possui_campanha" INTEGER NOT NULL,
    "status_esportes" INTEGER,
    "id_criador" INTEGER,
    "id_proprietario" INTEGER,
    "id_laboratorio" INTEGER,
    "exibe_laudo" BOOLEAN NOT NULL,
    "acesso_laboratorio" TEXT NOT NULL,
    "situacao_esportes" TEXT,
    "hall_da_fama" INTEGER,
    "qtdFilhos" INTEGER,
    "somaPontos" INTEGER,
    "qtdFilhosComPontos" INTEGER,
    "hall_da_fama_pessoa" INTEGER,
    "qtdFilhosMachoPontuados" INTEGER,
    "qtdFilhosFemeaPontuados" INTEGER,
    "qtdFilhosMacho" INTEGER,
    "qtdFilhosFemea" INTEGER,
    "userId" INTEGER NOT NULL,

    CONSTRAINT "animals_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "animal_ancestral" (
    "id_pai" INTEGER,
    "nome_pai" TEXT,
    "registro_pai" TEXT,
    "registro_original_pai" TEXT,
    "pelagem_pai" TEXT,
    "hypp_pai" INTEGER,
    "impressive_pai" INTEGER,
    "id_mae" INTEGER,
    "nome_mae" TEXT,
    "registro_mae" TEXT,
    "registro_original_mae" TEXT,
    "pelagem_mae" TEXT,
    "hypp_mae" INTEGER,
    "impressive_mae" INTEGER,
    "id_pai_1" INTEGER,
    "nome_pai_1" TEXT,
    "registro_pai_1" TEXT,
    "registro_original_pai_1" TEXT,
    "pelagem_pai_1" TEXT,
    "hypp_pai_1" INTEGER,
    "impressive_pai_1" INTEGER,
    "id_mae_1" INTEGER,
    "nome_mae_1" TEXT,
    "registro_mae_1" TEXT,
    "registro_original_mae_1" TEXT,
    "pelagem_mae_1" TEXT,
    "hypp_mae_1" INTEGER,
    "impressive_mae_1" INTEGER,
    "id_pai_2" INTEGER,
    "nome_pai_2" TEXT,
    "registro_pai_2" TEXT,
    "registro_original_pai_2" TEXT,
    "pelagem_pai_2" TEXT,
    "hypp_pai_2" INTEGER,
    "impressive_pai_2" INTEGER,
    "id_mae_2" INTEGER,
    "nome_mae_2" TEXT,
    "registro_mae_2" TEXT,
    "registro_original_mae_2" TEXT,
    "pelagem_mae_2" TEXT,
    "hypp_mae_2" INTEGER,
    "impressive_mae_2" INTEGER,
    "id_pai_3" INTEGER,
    "nome_pai_3" TEXT,
    "registro_pai_3" TEXT,
    "registro_original_pai_3" TEXT,
    "pelagem_pai_3" TEXT,
    "hypp_pai_3" INTEGER,
    "impressive_pai_3" INTEGER,
    "id_mae_3" INTEGER,
    "nome_mae_3" TEXT,
    "registro_mae_3" TEXT,
    "registro_original_mae_3" TEXT,
    "pelagem_mae_3" TEXT,
    "hypp_mae_3" INTEGER,
    "impressive_mae_3" INTEGER,
    "id_pai_4" INTEGER,
    "nome_pai_4" TEXT,
    "registro_pai_4" TEXT,
    "registro_original_pai_4" TEXT,
    "pelagem_pai_4" TEXT,
    "hypp_pai_4" INTEGER,
    "impressive_pai_4" INTEGER,
    "id_mae_4" INTEGER,
    "nome_mae_4" TEXT,
    "registro_mae_4" TEXT,
    "registro_original_mae_4" TEXT,
    "pelagem_mae_4" TEXT,
    "hypp_mae_4" INTEGER,
    "impressive_mae_4" INTEGER,
    "id_pai_5" INTEGER,
    "nome_pai_5" TEXT,
    "registro_pai_5" TEXT,
    "registro_original_pai_5" TEXT,
    "pelagem_pai_5" TEXT,
    "hypp_pai_5" INTEGER,
    "impressive_pai_5" INTEGER,
    "id_mae_5" INTEGER,
    "nome_mae_5" TEXT,
    "registro_mae_5" TEXT,
    "registro_original_mae_5" TEXT,
    "pelagem_mae_5" TEXT,
    "hypp_mae_5" INTEGER,
    "impressive_mae_5" INTEGER,
    "id_pai_6" INTEGER,
    "nome_pai_6" TEXT,
    "registro_pai_6" TEXT,
    "registro_original_pai_6" TEXT,
    "pelagem_pai_6" TEXT,
    "hypp_pai_6" INTEGER,
    "impressive_pai_6" INTEGER,
    "id_mae_6" INTEGER,
    "nome_mae_6" TEXT,
    "registro_mae_6" TEXT,
    "registro_original_mae_6" TEXT,
    "pelagem_mae_6" TEXT,
    "hypp_mae_6" INTEGER,
    "impressive_mae_6" INTEGER,
    "id_pai_7" INTEGER,
    "nome_pai_7" TEXT,
    "registro_pai_7" TEXT,
    "registro_original_pai_7" TEXT,
    "pelagem_pai_7" TEXT,
    "hypp_pai_7" INTEGER,
    "impressive_pai_7" INTEGER,
    "id_mae_7" INTEGER,
    "nome_mae_7" TEXT,
    "registro_mae_7" TEXT,
    "registro_original_mae_7" TEXT,
    "pelagem_mae_7" TEXT,
    "hypp_mae_7" INTEGER,
    "impressive_mae_7" INTEGER,
    "id_pai_8" INTEGER,
    "nome_pai_8" TEXT,
    "registro_pai_8" TEXT,
    "registro_original_pai_8" TEXT,
    "pelagem_pai_8" TEXT,
    "hypp_pai_8" INTEGER,
    "impressive_pai_8" INTEGER,
    "id_mae_8" INTEGER,
    "nome_mae_8" TEXT,
    "registro_mae_8" TEXT,
    "registro_original_mae_8" TEXT,
    "pelagem_mae_8" TEXT,
    "hypp_mae_8" INTEGER,
    "impressive_mae_8" INTEGER,
    "id_pai_9" INTEGER,
    "nome_pai_9" TEXT,
    "registro_pai_9" TEXT,
    "registro_original_pai_9" TEXT,
    "pelagem_pai_9" TEXT,
    "hypp_pai_9" INTEGER,
    "impressive_pai_9" INTEGER,
    "id_mae_9" INTEGER,
    "nome_mae_9" TEXT,
    "registro_mae_9" TEXT,
    "registro_original_mae_9" TEXT,
    "pelagem_mae_9" TEXT,
    "hypp_mae_9" INTEGER,
    "impressive_mae_9" INTEGER,
    "id_pai_10" INTEGER,
    "nome_pai_10" TEXT,
    "registro_pai_10" TEXT,
    "registro_original_pai_10" TEXT,
    "pelagem_pai_10" TEXT,
    "hypp_pai_10" INTEGER,
    "impressive_pai_10" INTEGER,
    "id_mae_10" INTEGER,
    "nome_mae_10" TEXT,
    "registro_mae_10" TEXT,
    "registro_original_mae_10" TEXT,
    "pelagem_mae_10" TEXT,
    "hypp_mae_10" INTEGER,
    "impressive_mae_10" INTEGER,
    "id_pai_11" INTEGER,
    "nome_pai_11" TEXT,
    "registro_pai_11" TEXT,
    "registro_original_pai_11" TEXT,
    "pelagem_pai_11" TEXT,
    "hypp_pai_11" INTEGER,
    "impressive_pai_11" INTEGER,
    "id_mae_11" INTEGER,
    "nome_mae_11" TEXT,
    "registro_mae_11" TEXT,
    "registro_original_mae_11" TEXT,
    "pelagem_mae_11" TEXT,
    "hypp_mae_11" INTEGER,
    "impressive_mae_11" INTEGER,
    "id_pai_12" INTEGER,
    "nome_pai_12" TEXT,
    "registro_pai_12" TEXT,
    "registro_original_pai_12" TEXT,
    "pelagem_pai_12" TEXT,
    "hypp_pai_12" INTEGER,
    "impressive_pai_12" INTEGER,
    "id_mae_12" INTEGER,
    "nome_mae_12" TEXT,
    "registro_mae_12" TEXT,
    "registro_original_mae_12" TEXT,
    "pelagem_mae_12" TEXT,
    "hypp_mae_12" INTEGER,
    "impressive_mae_12" INTEGER,
    "id_pai_13" INTEGER,
    "nome_pai_13" TEXT,
    "registro_pai_13" TEXT,
    "registro_original_pai_13" TEXT,
    "pelagem_pai_13" TEXT,
    "hypp_pai_13" INTEGER,
    "impressive_pai_13" INTEGER,
    "id_mae_13" INTEGER,
    "nome_mae_13" TEXT,
    "registro_mae_13" TEXT,
    "registro_original_mae_13" TEXT,
    "pelagem_mae_13" TEXT,
    "hypp_mae_13" INTEGER,
    "impressive_mae_13" INTEGER,
    "id_pai_14" INTEGER,
    "nome_pai_14" TEXT,
    "registro_pai_14" TEXT,
    "registro_original_pai_14" TEXT,
    "pelagem_pai_14" TEXT,
    "hypp_pai_14" INTEGER,
    "impressive_pai_14" INTEGER,
    "id_mae_14" INTEGER,
    "nome_mae_14" TEXT,
    "registro_mae_14" TEXT,
    "registro_original_mae_14" TEXT,
    "pelagem_mae_14" TEXT,
    "hypp_mae_14" INTEGER,
    "impressive_mae_14" INTEGER,
    "animalId" INTEGER NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "users_email_key" ON "users"("email");

-- CreateIndex
CREATE UNIQUE INDEX "animals_id_animal_key" ON "animals"("id_animal");

-- CreateIndex
CREATE UNIQUE INDEX "animal_ancestral_animalId_key" ON "animal_ancestral"("animalId");

-- AddForeignKey
ALTER TABLE "animals" ADD CONSTRAINT "animals_userId_fkey" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "animal_ancestral" ADD CONSTRAINT "animal_ancestral_animalId_fkey" FOREIGN KEY ("animalId") REFERENCES "animals"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
