import { Request, Response } from "express";
import { fetchAnimaisDoProprietario } from "../utils/propertySearch";
import { prisma } from "../database/prisma";
import { getToken } from "../auth/login";
import { fetchAnimalPorNomeRegistro } from "../utils/stringSearch";
import { getGenealogy } from "../utils/genealogySearch";
import { AppError } from "../utils/AppError";
interface Animal {
  indice: number;
  id_animal: number;
  certificado_registro: string;
  registro: string;
  nome: string;
  sexo: string;
  pelagem: string;
  sangue: string;
  data_nascimento: string;
  ativo_studbook: number;
  ativo_sports: number;
  castrado: number;
  obito: number;
  img_animal: string | null;
  obs_impressao: string;
  permite_impressao: boolean;
}

export class UsersController {
  async create(req: Request, res: Response) {
    const { email, senha } = req.body;
    const { data } = await fetchAnimaisDoProprietario(req.abqmToken);

    const user = await prisma.user.findUnique({
      where: {
        email: email,
      },
    });
    if (!user) {
      const dataOwner = await getToken(email, senha);
      const nome = dataOwner.fields.nome_pessoa;
      await prisma.user.create({
        data: { email, nome, senha },
      });
      data.forEach(async (item: Animal) => {
        const infoAnimal = await fetchAnimalPorNomeRegistro(
          item.registro,
          req.abqmToken
        );
        const userId = await prisma.user.findUnique({
          where: {
            email: email,
          },
          select: {
            id: true,
          },
        });
        if (!userId) {
          return;
        }
        const userIdNumber = userId.id;

        const {
          id_animal,
          id_cobertura,
          nome_animal,
          registro_abqm,
          registro_original,
          sufixo_nome_animal,
          sexo_animal,
          dt_nascimento,
          dt_castracao,
          dt_alteracao,
          dt_obito,
          dsc_grau_sangue,
          ds_pelagem,
          nome_proprietario,
          nome_comprador,
          nome_criador,
          id_pai,
          nome_pai,
          registro_pai,
          id_mae,
          nome_mae,
          registro_mae,
          tipificacao_sanguinea,
          DNA_LINK,
          hypp,
          hypp_string,
          five_panel,
          motivo_castracao,
          path_fotos,
          nro_chip,
          qtd_chip,
          dt_implantacao,
          alienado,
          arrendado,
          chave,
          dt_fim_temp_transf_emb,
          pontos,
          pk_imagem,
          placa,
          pdf,
          artigo_43,
          resenha,
          situacao,
          id_resultado_laboratorio,
          imagens,
          acessos,
          situacao_laboratorio,
          impressive,
          num_preregistro,
          dt_importacao,
          dt_inclusao_lancamento,
          dt_inclusao_situacao,
          dt_inclusao,
          dt_envio_doc,
          linkchip,
          possui_campanha,
          status_esportes,
          id_criador,
          id_proprietario,
          id_laboratorio,
          exibe_laudo,
          acesso_laboratorio,
          situacao_esportes,
          hall_da_fama,
          qtdFilhos,
          somaPontos,
          qtdFilhosComPontos,
          hall_da_fama_pessoa,
          qtdFilhosMachoPontuados,
          qtdFilhosFemeaPontuados,
          qtdFilhosMacho,
          qtdFilhosFemea,
        } = infoAnimal;
        await prisma.animal.create({
          data: {
            id_animal,
            id_cobertura,
            nome_animal,
            registro_abqm,
            registro_original,
            sufixo_nome_animal,
            sexo_animal,
            dt_nascimento,
            dt_castracao,
            dt_alteracao,
            dt_obito,
            dsc_grau_sangue,
            ds_pelagem,
            nome_proprietario,
            nome_comprador,
            nome_criador,
            id_pai,
            nome_pai,
            registro_pai,
            id_mae,
            nome_mae,
            registro_mae,
            tipificacao_sanguinea,
            DNA_LINK,
            hypp,
            hypp_string,
            five_panel,
            motivo_castracao,
            path_fotos,
            nro_chip,
            qtd_chip,
            dt_implantacao,
            alienado,
            arrendado,
            chave,
            dt_fim_temp_transf_emb,
            pontos,
            pk_imagem,
            placa,
            pdf,
            artigo_43,
            resenha,
            situacao,
            id_resultado_laboratorio,
            imagens,
            acessos,
            situacao_laboratorio,
            impressive,
            num_preregistro,
            dt_importacao,
            dt_inclusao_lancamento,
            dt_inclusao_situacao,
            dt_inclusao,
            dt_envio_doc,
            linkchip,
            possui_campanha,
            status_esportes,
            id_criador,
            id_proprietario,
            id_laboratorio,
            exibe_laudo,
            acesso_laboratorio,
            situacao_esportes,
            hall_da_fama,
            qtdFilhos,
            somaPontos,
            qtdFilhosComPontos,
            hall_da_fama_pessoa,
            qtdFilhosMachoPontuados,
            qtdFilhosFemeaPontuados,
            qtdFilhosMacho,
            qtdFilhosFemea,
            userId: userIdNumber, // <-- se estiver relacionando o animal com o usuário
          },
        });
        const animalId = await prisma.animal.findFirst({
          orderBy: { id: "desc" },
          select: { id: true },
        });
        const dataGenealogy = await getGenealogy(item.id_animal, req.abqmToken);
        if (!animalId) {
          return;
        }
        const {
          nome_pai: nome_pai_g,
          registro_pai: registro_pai_g,
          registro_original_pai,
          pelagem_pai,
          hypp_pai,
          impressive_pai,
          id_mae: id_mae_g,
          nome_mae: nome_mae_g,
          registro_mae: registro_mae_g,
          registro_original_mae,
          pelagem_mae,
          hypp_mae,
          impressive_mae,
          id_pai_1,
          nome_pai_1,
          registro_pai_1,
          registro_original_pai_1,
          pelagem_pai_1,
          hypp_pai_1,
          impressive_pai_1,
          id_mae_1,
          nome_mae_1,
          registro_mae_1,
          registro_original_mae_1,
          pelagem_mae_1,
          hypp_mae_1,
          impressive_mae_1,
          id_pai_2,
          nome_pai_2,
          registro_pai_2,
          registro_original_pai_2,
          pelagem_pai_2,
          hypp_pai_2,
          impressive_pai_2,
          id_mae_2,
          nome_mae_2,
          registro_mae_2,
          registro_original_mae_2,
          pelagem_mae_2,
          hypp_mae_2,
          impressive_mae_2,
          id_pai_3,
          nome_pai_3,
          registro_pai_3,
          registro_original_pai_3,
          pelagem_pai_3,
          hypp_pai_3,
          impressive_pai_3,
          id_mae_3,
          nome_mae_3,
          registro_mae_3,
          registro_original_mae_3,
          pelagem_mae_3,
          hypp_mae_3,
          impressive_mae_3,
          id_pai_4,
          nome_pai_4,
          registro_pai_4,
          registro_original_pai_4,
          pelagem_pai_4,
          hypp_pai_4,
          impressive_pai_4,
          id_mae_4,
          nome_mae_4,
          registro_mae_4,
          registro_original_mae_4,
          pelagem_mae_4,
          hypp_mae_4,
          impressive_mae_4,
          id_pai_5,
          nome_pai_5,
          registro_pai_5,
          registro_original_pai_5,
          pelagem_pai_5,
          hypp_pai_5,
          impressive_pai_5,
          id_mae_5,
          nome_mae_5,
          registro_mae_5,
          registro_original_mae_5,
          pelagem_mae_5,
          hypp_mae_5,
          impressive_mae_5,
          id_pai_6,
          nome_pai_6,
          registro_pai_6,
          registro_original_pai_6,
          pelagem_pai_6,
          hypp_pai_6,
          impressive_pai_6,
          id_mae_6,
          nome_mae_6,
          registro_mae_6,
          registro_original_mae_6,
          pelagem_mae_6,
          hypp_mae_6,
          impressive_mae_6,
          id_pai_7,
          nome_pai_7,
          registro_pai_7,
          registro_original_pai_7,
          pelagem_pai_7,
          hypp_pai_7,
          impressive_pai_7,
          id_mae_7,
          nome_mae_7,
          registro_mae_7,
          registro_original_mae_7,
          pelagem_mae_7,
          hypp_mae_7,
          impressive_mae_7,
          id_pai_8,
          nome_pai_8,
          registro_pai_8,
          registro_original_pai_8,
          pelagem_pai_8,
          hypp_pai_8,
          impressive_pai_8,
          id_mae_8,
          nome_mae_8,
          registro_mae_8,
          registro_original_mae_8,
          pelagem_mae_8,
          hypp_mae_8,
          impressive_mae_8,
          id_pai_9,
          nome_pai_9,
          registro_pai_9,
          registro_original_pai_9,
          pelagem_pai_9,
          hypp_pai_9,
          impressive_pai_9,
          id_mae_9,
          nome_mae_9,
          registro_mae_9,
          registro_original_mae_9,
          pelagem_mae_9,
          hypp_mae_9,
          impressive_mae_9,
          id_pai_10,
          nome_pai_10,
          registro_pai_10,
          registro_original_pai_10,
          pelagem_pai_10,
          hypp_pai_10,
          impressive_pai_10,
          id_mae_10,
          nome_mae_10,
          registro_mae_10,
          registro_original_mae_10,
          pelagem_mae_10,
          hypp_mae_10,
          impressive_mae_10,
          id_pai_11,
          nome_pai_11,
          registro_pai_11,
          registro_original_pai_11,
          pelagem_pai_11,
          hypp_pai_11,
          impressive_pai_11,
          id_mae_11,
          nome_mae_11,
          registro_mae_11,
          registro_original_mae_11,
          pelagem_mae_11,
          hypp_mae_11,
          impressive_mae_11,
          id_pai_12,
          nome_pai_12,
          registro_pai_12,
          registro_original_pai_12,
          pelagem_pai_12,
          hypp_pai_12,
          impressive_pai_12,
          id_mae_12,
          nome_mae_12,
          registro_mae_12,
          registro_original_mae_12,
          pelagem_mae_12,
          hypp_mae_12,
          impressive_mae_12,
          id_pai_13,
          nome_pai_13,
          registro_pai_13,
          registro_original_pai_13,
          pelagem_pai_13,
          hypp_pai_13,
          impressive_pai_13,
          id_mae_13,
          nome_mae_13,
          registro_mae_13,
          registro_original_mae_13,
          pelagem_mae_13,
          hypp_mae_13,
          impressive_mae_13,
          id_pai_14,
          nome_pai_14,
          registro_pai_14,
          registro_original_pai_14,
          pelagem_pai_14,
          hypp_pai_14,
          impressive_pai_14,
          id_mae_14,
          nome_mae_14,
          registro_mae_14,
          registro_original_mae_14,
          pelagem_mae_14,
          hypp_mae_14,
          impressive_mae_14,
        } = dataGenealogy;
        await prisma.animalAncestral.create({
          data: {
            nome_pai: nome_pai_g,
            registro_pai: registro_pai_g,
            registro_original_pai,
            pelagem_pai,
            hypp_pai,
            impressive_pai,
            id_mae: id_mae_g,
            nome_mae: nome_mae_g,
            registro_mae: registro_mae_g,
            registro_original_mae,
            pelagem_mae,
            hypp_mae,
            impressive_mae,

            id_pai_1,
            nome_pai_1,
            registro_pai_1,
            registro_original_pai_1,
            pelagem_pai_1,
            hypp_pai_1,
            impressive_pai_1,
            id_mae_1,
            nome_mae_1,
            registro_mae_1,
            registro_original_mae_1,
            pelagem_mae_1,
            hypp_mae_1,
            impressive_mae_1,

            id_pai_2,
            nome_pai_2,
            registro_pai_2,
            registro_original_pai_2,
            pelagem_pai_2,
            hypp_pai_2,
            impressive_pai_2,
            id_mae_2,
            nome_mae_2,
            registro_mae_2,
            registro_original_mae_2,
            pelagem_mae_2,
            hypp_mae_2,
            impressive_mae_2,

            id_pai_3,
            nome_pai_3,
            registro_pai_3,
            registro_original_pai_3,
            pelagem_pai_3,
            hypp_pai_3,
            impressive_pai_3,
            id_mae_3,
            nome_mae_3,
            registro_mae_3,
            registro_original_mae_3,
            pelagem_mae_3,
            hypp_mae_3,
            impressive_mae_3,

            id_pai_4,
            nome_pai_4,
            registro_pai_4,
            registro_original_pai_4,
            pelagem_pai_4,
            hypp_pai_4,
            impressive_pai_4,
            id_mae_4,
            nome_mae_4,
            registro_mae_4,
            registro_original_mae_4,
            pelagem_mae_4,
            hypp_mae_4,
            impressive_mae_4,

            id_pai_5,
            nome_pai_5,
            registro_pai_5,
            registro_original_pai_5,
            pelagem_pai_5,
            hypp_pai_5,
            impressive_pai_5,
            id_mae_5,
            nome_mae_5,
            registro_mae_5,
            registro_original_mae_5,
            pelagem_mae_5,
            hypp_mae_5,
            impressive_mae_5,

            id_pai_6,
            nome_pai_6,
            registro_pai_6,
            registro_original_pai_6,
            pelagem_pai_6,
            hypp_pai_6,
            impressive_pai_6,
            id_mae_6,
            nome_mae_6,
            registro_mae_6,
            registro_original_mae_6,
            pelagem_mae_6,
            hypp_mae_6,
            impressive_mae_6,

            id_pai_7,
            nome_pai_7,
            registro_pai_7,
            registro_original_pai_7,
            pelagem_pai_7,
            hypp_pai_7,
            impressive_pai_7,
            id_mae_7,
            nome_mae_7,
            registro_mae_7,
            registro_original_mae_7,
            pelagem_mae_7,
            hypp_mae_7,
            impressive_mae_7,

            id_pai_8,
            nome_pai_8,
            registro_pai_8,
            registro_original_pai_8,
            pelagem_pai_8,
            hypp_pai_8,
            impressive_pai_8,
            id_mae_8,
            nome_mae_8,
            registro_mae_8,
            registro_original_mae_8,
            pelagem_mae_8,
            hypp_mae_8,
            impressive_mae_8,

            id_pai_9,
            nome_pai_9,
            registro_pai_9,
            registro_original_pai_9,
            pelagem_pai_9,
            hypp_pai_9,
            impressive_pai_9,
            id_mae_9,
            nome_mae_9,
            registro_mae_9,
            registro_original_mae_9,
            pelagem_mae_9,
            hypp_mae_9,
            impressive_mae_9,

            id_pai_10,
            nome_pai_10,
            registro_pai_10,
            registro_original_pai_10,
            pelagem_pai_10,
            hypp_pai_10,
            impressive_pai_10,
            id_mae_10,
            nome_mae_10,
            registro_mae_10,
            registro_original_mae_10,
            pelagem_mae_10,
            hypp_mae_10,
            impressive_mae_10,

            id_pai_11,
            nome_pai_11,
            registro_pai_11,
            registro_original_pai_11,
            pelagem_pai_11,
            hypp_pai_11,
            impressive_pai_11,
            id_mae_11,
            nome_mae_11,
            registro_mae_11,
            registro_original_mae_11,
            pelagem_mae_11,
            hypp_mae_11,
            impressive_mae_11,

            id_pai_12,
            nome_pai_12,
            registro_pai_12,
            registro_original_pai_12,
            pelagem_pai_12,
            hypp_pai_12,
            impressive_pai_12,
            id_mae_12,
            nome_mae_12,
            registro_mae_12,
            registro_original_mae_12,
            pelagem_mae_12,
            hypp_mae_12,
            impressive_mae_12,

            id_pai_13,
            nome_pai_13,
            registro_pai_13,
            registro_original_pai_13,
            pelagem_pai_13,
            hypp_pai_13,
            impressive_pai_13,
            id_mae_13,
            nome_mae_13,
            registro_mae_13,
            registro_original_mae_13,
            pelagem_mae_13,
            hypp_mae_13,
            impressive_mae_13,

            id_pai_14,
            nome_pai_14,
            registro_pai_14,
            registro_original_pai_14,
            pelagem_pai_14,
            hypp_pai_14,
            impressive_pai_14,
            id_mae_14,
            nome_mae_14,
            registro_mae_14,
            registro_original_mae_14,
            pelagem_mae_14,
            hypp_mae_14,
            impressive_mae_14,
            animalId: animalId.id,
          },
        });
      });
    }
    // VERIFICAR SE JA TEM ESSE EMAIL CADASTRADO NO MEU BANCO
    // SE NÂO TIVER É NECESSARIO GRAVAR INFO DO USER, ANIMAL E GENEALOGIA
    res.json("Criado");
  }
}
